PRESET_ITEMS = (
    ("GENERIC", "Generic Broadleaf", "Balanced broadleaf starting point"),
    ("OAK", "English Oak", "Broad irregular crown with heavy limbs"),
    ("HOLM_OAK", "Holm Oak", "Dense rounded evergreen Mediterranean oak"),
    ("CORK_OAK", "Cork Oak", "Low, rugged Mediterranean oak with spreading limbs"),
    ("BIRCH", "Silver Birch", "Slender trunk and airy drooping crown"),
    ("BEECH", "European Beech", "Tall clean trunk with dense smooth crown"),
    ("MAPLE", "Maple", "Balanced rounded crown with strong secondary branching"),
    ("ASH", "Ash", "Open oval crown with upward-reaching branches"),
    ("ELM", "Elm", "Vase-shaped crown with arching limbs"),
    ("LINDEN", "Linden / Lime", "Dense regular oval crown"),
    ("CHESTNUT", "Sweet Chestnut", "Large broad crown with stout twisting branches"),
    ("WALNUT", "Walnut", "Open broad crown with fewer heavy limbs"),
    ("PLANE", "London Plane", "Large high crown and massive urban-tree structure"),
    ("ALDER", "Alder", "Moderately narrow wetland broadleaf"),
    ("ASPEN", "Aspen", "Slender trunk with light high crown"),
    ("POPLAR", "Lombardy Poplar", "Very tall narrow columnar crown"),
    ("WILLOW", "Weeping Willow", "Wide crown with strongly drooping branches"),
    ("CHERRY", "Cherry", "Compact rounded ornamental crown"),
    ("APPLE", "Apple", "Low irregular orchard tree with spreading crown"),
    ("MAGNOLIA", "Magnolia", "Dense rounded ornamental crown with large foliage cards"),
    ("JACARANDA", "Jacaranda", "Open umbrella crown with delicate branch structure"),
    ("EUCALYPTUS", "Eucalyptus", "Tall sparse crown with irregular upward limbs"),
    ("OLIVE", "Olive", "Short ancient-looking Mediterranean tree with twisted crown"),
    ("ACACIA", "Umbrella Acacia", "Flat wide savanna crown"),
    ("BAOBAB", "Baobab", "Very thick trunk with sparse high crown"),
    ("PINE", "Scots Pine", "Conical-to-open pine silhouette"),
    ("STONE_PINE", "Stone Pine", "Tall trunk with broad umbrella pine crown"),
    ("SPRUCE", "Norway Spruce", "Dense conical conifer with drooping laterals"),
    ("FIR", "Silver Fir", "Regular conical conifer with layered branches"),
    ("CEDAR", "Cedar", "Broad tiered evergreen crown"),
    ("CYPRESS", "Italian Cypress", "Extremely narrow columnar evergreen"),
    ("REDWOOD", "Coast Redwood", "Very tall conical evergreen with massive trunk"),
    ("DEAD_TREE", "Dead Tree", "Bare weathered tree with dead and pruned branches"),
    ("WINDSWEPT", "Windswept", "Asymmetric low-density tree for exposed terrain"),
    ("SAPLING", "Young Sapling", "Small young tree with simple branching"),
)


PRESETS = {
    "GENERIC": {
        "height": 12.0, "base_radius": 0.45, "trunk_irregularity": 0.12, "trunk_taper": 0.92,
        "root_flare": 0.35, "crown_shape": "ROUND", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.24, "primary_branches": 20, "secondary_per_branch": 3,
        "branch_angle": 1.02, "branch_length": 4.4, "branch_bend": 0.16, "branch_droop": 0.16,
        "apical_dominance": 0.42, "phototropism": 0.18, "branch_collar": 0.32,
        "dead_branch_probability": 0.02, "prune_probability": 0.035,
        "foliage_density": 1.0, "foliage_start": 0.48, "foliage_tip_bias": 0.65,
        "foliage_spread": 0.55, "leaf_up_bias": 0.55,
        "card_scale": 0.72, "card_aspect": 1.25, "card_style": "CROSS",
    },
    "OAK": {
        "height": 15.0, "base_radius": 0.72, "trunk_irregularity": 0.22, "trunk_taper": 0.82,
        "root_flare": 0.65, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.28, "primary_branches": 18, "secondary_per_branch": 4,
        "branch_angle": 1.12, "branch_length": 6.5, "branch_length_randomness": 0.38,
        "branch_bend": 0.28, "branch_droop": 0.12, "apical_dominance": 0.18, "phototropism": 0.12,
        "branch_collar": 0.55, "dead_branch_probability": 0.035, "prune_probability": 0.04,
        "foliage_density": 1.15, "foliage_start": 0.46, "foliage_tip_bias": 0.58,
        "foliage_spread": 0.75, "leaf_up_bias": 0.48,
        "card_scale": 0.82, "card_aspect": 1.15, "card_style": "TRI",
    },
    "HOLM_OAK": {
        "height": 11.0, "base_radius": 0.62, "trunk_irregularity": 0.24, "trunk_taper": 0.86,
        "root_flare": 0.62, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.22, "primary_branches": 22, "secondary_per_branch": 4,
        "branch_angle": 1.18, "branch_length": 5.2, "branch_length_randomness": 0.34,
        "branch_bend": 0.27, "branch_droop": 0.10, "apical_dominance": 0.15, "phototropism": 0.10,
        "branch_collar": 0.48, "dead_branch_probability": 0.035, "prune_probability": 0.04,
        "foliage_density": 1.48, "foliage_start": 0.42, "foliage_tip_bias": 0.58,
        "foliage_spread": 0.68, "leaf_up_bias": 0.48,
        "card_scale": 0.62, "card_aspect": 1.05, "card_style": "TRI",
    },
    "CORK_OAK": {
        "height": 10.0, "base_radius": 0.70, "trunk_irregularity": 0.34, "trunk_taper": 0.78,
        "root_flare": 0.86, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.20, "primary_branches": 15, "secondary_per_branch": 4,
        "branch_angle": 1.22, "branch_length": 5.5, "branch_length_randomness": 0.44,
        "branch_bend": 0.36, "branch_droop": 0.14, "apical_dominance": 0.10, "phototropism": 0.08,
        "branch_collar": 0.68, "dead_branch_probability": 0.06, "prune_probability": 0.055,
        "foliage_density": 1.18, "foliage_start": 0.48, "foliage_tip_bias": 0.62,
        "foliage_spread": 0.72, "leaf_up_bias": 0.50,
        "card_scale": 0.66, "card_aspect": 1.10, "card_style": "TRI",
    },
    "BIRCH": {
        "height": 16.0, "base_radius": 0.34, "trunk_irregularity": 0.10, "trunk_taper": 1.05,
        "root_flare": 0.22, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.34, "primary_branches": 24, "secondary_per_branch": 3,
        "branch_angle": 0.86, "branch_length": 3.5, "branch_length_randomness": 0.30,
        "branch_bend": 0.14, "branch_droop": 0.28, "apical_dominance": 0.62, "phototropism": 0.28,
        "branch_collar": 0.22, "dead_branch_probability": 0.025, "prune_probability": 0.055,
        "foliage_density": 0.88, "foliage_start": 0.54, "foliage_tip_bias": 0.72,
        "foliage_spread": 0.48, "leaf_up_bias": 0.58,
        "card_scale": 0.55, "card_aspect": 1.45, "card_style": "CROSS",
    },
    "BEECH": {
        "height": 20.0, "base_radius": 0.62, "trunk_irregularity": 0.055, "trunk_taper": 0.98,
        "root_flare": 0.48, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 4, "branch_start": 0.31, "primary_branches": 21, "secondary_per_branch": 4,
        "branch_angle": 1.00, "branch_length": 5.4, "branch_length_randomness": 0.20,
        "branch_bend": 0.12, "branch_droop": 0.10, "apical_dominance": 0.50, "phototropism": 0.24,
        "branch_collar": 0.34, "dead_branch_probability": 0.015, "prune_probability": 0.06,
        "foliage_density": 1.38, "foliage_start": 0.43, "foliage_tip_bias": 0.60,
        "foliage_spread": 0.58, "leaf_up_bias": 0.58,
        "card_scale": 0.68, "card_aspect": 1.18, "card_style": "TRI",
    },
    "MAPLE": {
        "height": 14.0, "base_radius": 0.53, "trunk_irregularity": 0.13, "trunk_taper": 0.92,
        "root_flare": 0.40, "crown_shape": "ROUND", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 4, "branch_start": 0.27, "primary_branches": 23, "secondary_per_branch": 4,
        "branch_angle": 1.04, "branch_length": 5.0, "branch_length_randomness": 0.28,
        "branch_bend": 0.18, "branch_droop": 0.10, "apical_dominance": 0.32, "phototropism": 0.20,
        "branch_collar": 0.34, "dead_branch_probability": 0.02, "prune_probability": 0.035,
        "foliage_density": 1.32, "foliage_start": 0.45, "foliage_tip_bias": 0.61,
        "foliage_spread": 0.66, "leaf_up_bias": 0.55,
        "card_scale": 0.78, "card_aspect": 1.15, "card_style": "TRI",
    },
    "ASH": {
        "height": 19.0, "base_radius": 0.55, "trunk_irregularity": 0.10, "trunk_taper": 1.00,
        "root_flare": 0.34, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.30, "primary_branches": 18, "secondary_per_branch": 3,
        "branch_angle": 0.88, "branch_length": 5.4, "branch_length_randomness": 0.30,
        "branch_bend": 0.13, "branch_droop": 0.05, "apical_dominance": 0.48, "phototropism": 0.36,
        "branch_collar": 0.30, "dead_branch_probability": 0.025, "prune_probability": 0.055,
        "foliage_density": 0.78, "foliage_start": 0.53, "foliage_tip_bias": 0.73,
        "foliage_spread": 0.50, "leaf_up_bias": 0.62,
        "card_scale": 0.64, "card_aspect": 1.45, "card_style": "CROSS",
    },
    "ELM": {
        "height": 18.0, "base_radius": 0.66, "trunk_irregularity": 0.18, "trunk_taper": 0.90,
        "root_flare": 0.58, "crown_shape": "VASE", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.24, "primary_branches": 17, "secondary_per_branch": 4,
        "branch_angle": 0.82, "branch_length": 6.0, "branch_length_randomness": 0.32,
        "branch_bend": 0.24, "branch_droop": 0.08, "apical_dominance": 0.25, "phototropism": 0.42,
        "branch_collar": 0.44, "dead_branch_probability": 0.03, "prune_probability": 0.04,
        "foliage_density": 1.08, "foliage_start": 0.47, "foliage_tip_bias": 0.68,
        "foliage_spread": 0.65, "leaf_up_bias": 0.60,
        "card_scale": 0.70, "card_aspect": 1.22, "card_style": "TRI",
    },
    "LINDEN": {
        "height": 17.0, "base_radius": 0.57, "trunk_irregularity": 0.08, "trunk_taper": 0.96,
        "root_flare": 0.36, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 4, "branch_start": 0.27, "primary_branches": 25, "secondary_per_branch": 4,
        "branch_angle": 1.00, "branch_length": 5.1, "branch_length_randomness": 0.20,
        "branch_bend": 0.13, "branch_droop": 0.08, "apical_dominance": 0.43, "phototropism": 0.22,
        "branch_collar": 0.31, "dead_branch_probability": 0.015, "prune_probability": 0.035,
        "foliage_density": 1.48, "foliage_start": 0.41, "foliage_tip_bias": 0.58,
        "foliage_spread": 0.62, "leaf_up_bias": 0.56,
        "card_scale": 0.70, "card_aspect": 1.20, "card_style": "TRI",
    },
    "CHESTNUT": {
        "height": 17.0, "base_radius": 0.72, "trunk_irregularity": 0.20, "trunk_taper": 0.86,
        "root_flare": 0.64, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.26, "primary_branches": 17, "secondary_per_branch": 4,
        "branch_angle": 1.10, "branch_length": 6.4, "branch_length_randomness": 0.36,
        "branch_bend": 0.26, "branch_droop": 0.12, "apical_dominance": 0.20, "phototropism": 0.12,
        "branch_collar": 0.52, "dead_branch_probability": 0.035, "prune_probability": 0.04,
        "foliage_density": 1.22, "foliage_start": 0.47, "foliage_tip_bias": 0.61,
        "foliage_spread": 0.76, "leaf_up_bias": 0.52,
        "card_scale": 0.82, "card_aspect": 1.30, "card_style": "TRI",
    },
    "WALNUT": {
        "height": 15.0, "base_radius": 0.62, "trunk_irregularity": 0.15, "trunk_taper": 0.90,
        "root_flare": 0.46, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 3, "branch_start": 0.30, "primary_branches": 14, "secondary_per_branch": 3,
        "branch_angle": 1.08, "branch_length": 6.0, "branch_length_randomness": 0.34,
        "branch_bend": 0.20, "branch_droop": 0.08, "apical_dominance": 0.26, "phototropism": 0.16,
        "branch_collar": 0.46, "dead_branch_probability": 0.025, "prune_probability": 0.04,
        "foliage_density": 0.90, "foliage_start": 0.53, "foliage_tip_bias": 0.69,
        "foliage_spread": 0.64, "leaf_up_bias": 0.54,
        "card_scale": 0.84, "card_aspect": 1.35, "card_style": "CROSS",
    },
    "PLANE": {
        "height": 22.0, "base_radius": 0.82, "trunk_irregularity": 0.12, "trunk_taper": 0.88,
        "root_flare": 0.68, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.32, "primary_branches": 19, "secondary_per_branch": 4,
        "branch_angle": 1.05, "branch_length": 7.3, "branch_length_randomness": 0.30,
        "branch_bend": 0.20, "branch_droop": 0.09, "apical_dominance": 0.28, "phototropism": 0.18,
        "branch_collar": 0.56, "dead_branch_probability": 0.025, "prune_probability": 0.045,
        "foliage_density": 1.18, "foliage_start": 0.46, "foliage_tip_bias": 0.62,
        "foliage_spread": 0.76, "leaf_up_bias": 0.54,
        "card_scale": 0.90, "card_aspect": 1.18, "card_style": "TRI",
    },
    "ALDER": {
        "height": 15.0, "base_radius": 0.46, "trunk_irregularity": 0.12, "trunk_taper": 1.00,
        "root_flare": 0.32, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.25, "primary_branches": 22, "secondary_per_branch": 3,
        "branch_angle": 0.96, "branch_length": 4.2, "branch_length_randomness": 0.28,
        "branch_bend": 0.14, "branch_droop": 0.11, "apical_dominance": 0.50, "phototropism": 0.25,
        "branch_collar": 0.27, "dead_branch_probability": 0.025, "prune_probability": 0.04,
        "foliage_density": 1.05, "foliage_start": 0.50, "foliage_tip_bias": 0.68,
        "foliage_spread": 0.52, "leaf_up_bias": 0.57,
        "card_scale": 0.65, "card_aspect": 1.18, "card_style": "CROSS",
    },
    "ASPEN": {
        "height": 17.0, "base_radius": 0.32, "trunk_irregularity": 0.055, "trunk_taper": 1.10,
        "root_flare": 0.18, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.40, "primary_branches": 20, "secondary_per_branch": 2,
        "branch_angle": 0.80, "branch_length": 3.2, "branch_length_randomness": 0.24,
        "branch_bend": 0.09, "branch_droop": 0.08, "apical_dominance": 0.70, "phototropism": 0.38,
        "branch_collar": 0.20, "dead_branch_probability": 0.015, "prune_probability": 0.07,
        "foliage_density": 0.82, "foliage_start": 0.56, "foliage_tip_bias": 0.74,
        "foliage_spread": 0.42, "leaf_up_bias": 0.60,
        "card_scale": 0.54, "card_aspect": 1.25, "card_style": "CROSS",
    },
    "POPLAR": {
        "height": 22.0, "base_radius": 0.48, "trunk_irregularity": 0.055, "trunk_taper": 1.12,
        "root_flare": 0.25, "crown_shape": "COLUMNAR", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.18, "primary_branches": 34, "secondary_per_branch": 2,
        "branch_angle": 0.56, "branch_length": 2.8, "branch_length_randomness": 0.18,
        "branch_bend": 0.08, "branch_droop": 0.02, "apical_dominance": 0.86, "phototropism": 0.52,
        "branch_collar": 0.20, "dead_branch_probability": 0.015, "prune_probability": 0.055,
        "foliage_density": 1.05, "foliage_start": 0.46, "foliage_tip_bias": 0.70,
        "foliage_spread": 0.38, "leaf_up_bias": 0.68,
        "card_scale": 0.58, "card_aspect": 1.35, "card_style": "CROSS",
    },
    "WILLOW": {
        "height": 13.0, "base_radius": 0.58, "trunk_irregularity": 0.20, "trunk_taper": 0.88,
        "root_flare": 0.42, "crown_shape": "UMBRELLA", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.30, "primary_branches": 22, "secondary_per_branch": 4,
        "branch_angle": 1.20, "branch_length": 6.0, "branch_length_randomness": 0.30,
        "branch_bend": 0.24, "branch_droop": 0.95, "apical_dominance": 0.14, "phototropism": -0.04,
        "branch_collar": 0.34, "dead_branch_probability": 0.025, "prune_probability": 0.02,
        "foliage_density": 1.35, "foliage_start": 0.43, "foliage_tip_bias": 0.80,
        "foliage_spread": 0.45, "leaf_up_bias": 0.30,
        "card_scale": 0.68, "card_aspect": 1.75, "card_style": "CROSS",
    },
    "CHERRY": {
        "height": 9.0, "base_radius": 0.38, "trunk_irregularity": 0.14, "trunk_taper": 0.88,
        "root_flare": 0.30, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.24, "primary_branches": 18, "secondary_per_branch": 4,
        "branch_angle": 1.12, "branch_length": 3.8, "branch_length_randomness": 0.30,
        "branch_bend": 0.18, "branch_droop": 0.10, "apical_dominance": 0.22, "phototropism": 0.18,
        "branch_collar": 0.34, "dead_branch_probability": 0.02, "prune_probability": 0.035,
        "foliage_density": 1.30, "foliage_start": 0.43, "foliage_tip_bias": 0.62,
        "foliage_spread": 0.58, "leaf_up_bias": 0.56,
        "card_scale": 0.62, "card_aspect": 1.12, "card_style": "TRI",
    },
    "APPLE": {
        "height": 6.5, "base_radius": 0.36, "trunk_irregularity": 0.22, "trunk_taper": 0.80,
        "root_flare": 0.38, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.18, "primary_branches": 14, "secondary_per_branch": 4,
        "branch_angle": 1.20, "branch_length": 3.2, "branch_length_randomness": 0.42,
        "branch_bend": 0.27, "branch_droop": 0.16, "apical_dominance": 0.08, "phototropism": 0.10,
        "branch_collar": 0.40, "dead_branch_probability": 0.045, "prune_probability": 0.035,
        "foliage_density": 1.15, "foliage_start": 0.47, "foliage_tip_bias": 0.64,
        "foliage_spread": 0.65, "leaf_up_bias": 0.50,
        "card_scale": 0.64, "card_aspect": 1.10, "card_style": "TRI",
    },
    "MAGNOLIA": {
        "height": 10.0, "base_radius": 0.42, "trunk_irregularity": 0.10, "trunk_taper": 0.90,
        "root_flare": 0.32, "crown_shape": "ROUND", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.20, "primary_branches": 20, "secondary_per_branch": 3,
        "branch_angle": 1.10, "branch_length": 4.0, "branch_length_randomness": 0.20,
        "branch_bend": 0.14, "branch_droop": 0.08, "apical_dominance": 0.28, "phototropism": 0.20,
        "branch_collar": 0.30, "dead_branch_probability": 0.01, "prune_probability": 0.025,
        "foliage_density": 1.48, "foliage_start": 0.40, "foliage_tip_bias": 0.56,
        "foliage_spread": 0.64, "leaf_up_bias": 0.62,
        "card_scale": 0.98, "card_aspect": 1.32, "card_style": "TRI",
    },
    "JACARANDA": {
        "height": 12.0, "base_radius": 0.44, "trunk_irregularity": 0.16, "trunk_taper": 0.92,
        "root_flare": 0.32, "crown_shape": "UMBRELLA", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.30, "primary_branches": 16, "secondary_per_branch": 5,
        "branch_angle": 1.12, "branch_length": 5.1, "branch_length_randomness": 0.34,
        "branch_bend": 0.21, "branch_droop": 0.12, "apical_dominance": 0.18, "phototropism": 0.18,
        "branch_collar": 0.32, "dead_branch_probability": 0.02, "prune_probability": 0.03,
        "foliage_density": 0.92, "foliage_start": 0.56, "foliage_tip_bias": 0.76,
        "foliage_spread": 0.56, "leaf_up_bias": 0.54,
        "card_scale": 0.58, "card_aspect": 1.18, "card_style": "CROSS",
    },
    "EUCALYPTUS": {
        "height": 24.0, "base_radius": 0.58, "trunk_irregularity": 0.16, "trunk_taper": 1.02,
        "root_flare": 0.42, "crown_shape": "OVAL", "branch_distribution": "RANDOM",
        "branch_levels": 3, "branch_start": 0.42, "primary_branches": 14, "secondary_per_branch": 3,
        "branch_angle": 0.82, "branch_length": 6.0, "branch_length_randomness": 0.42,
        "branch_bend": 0.24, "branch_droop": 0.04, "apical_dominance": 0.56, "phototropism": 0.38,
        "branch_collar": 0.33, "dead_branch_probability": 0.045, "prune_probability": 0.08,
        "foliage_density": 0.58, "foliage_start": 0.61, "foliage_tip_bias": 0.80,
        "foliage_spread": 0.48, "leaf_up_bias": 0.64,
        "card_scale": 0.58, "card_aspect": 1.75, "card_style": "CROSS",
    },
    "OLIVE": {
        "height": 7.5, "base_radius": 0.46, "trunk_irregularity": 0.42, "trunk_taper": 0.72,
        "root_flare": 0.82, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.24, "primary_branches": 13, "secondary_per_branch": 4,
        "branch_angle": 1.12, "branch_length": 3.6, "branch_length_randomness": 0.46,
        "branch_bend": 0.38, "branch_droop": 0.10, "apical_dominance": 0.08, "phototropism": 0.10,
        "branch_collar": 0.62, "dead_branch_probability": 0.07, "prune_probability": 0.05,
        "foliage_density": 1.05, "foliage_start": 0.50, "foliage_tip_bias": 0.72,
        "foliage_spread": 0.56, "leaf_up_bias": 0.52,
        "card_scale": 0.48, "card_aspect": 1.70, "card_style": "CROSS",
    },
    "ACACIA": {
        "height": 9.5, "base_radius": 0.42, "trunk_irregularity": 0.19, "trunk_taper": 0.86,
        "root_flare": 0.38, "crown_shape": "UMBRELLA", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.47, "primary_branches": 13, "secondary_per_branch": 4,
        "branch_angle": 1.30, "branch_length": 5.3, "branch_length_randomness": 0.34,
        "branch_bend": 0.19, "branch_droop": 0.03, "apical_dominance": 0.08, "phototropism": 0.05,
        "branch_collar": 0.38, "dead_branch_probability": 0.05, "prune_probability": 0.06,
        "foliage_density": 0.72, "foliage_start": 0.61, "foliage_tip_bias": 0.80,
        "foliage_spread": 0.72, "leaf_up_bias": 0.50,
        "card_scale": 0.58, "card_aspect": 1.15, "card_style": "TRI",
    },
    "BAOBAB": {
        "height": 13.0, "base_radius": 1.65, "trunk_irregularity": 0.16, "trunk_taper": 0.56,
        "root_flare": 1.35, "crown_shape": "UMBRELLA", "branch_distribution": "RANDOM",
        "branch_levels": 3, "branch_start": 0.58, "primary_branches": 11, "secondary_per_branch": 3,
        "branch_angle": 1.12, "branch_length": 5.1, "branch_length_randomness": 0.34,
        "branch_bend": 0.22, "branch_droop": 0.02, "apical_dominance": 0.06, "phototropism": 0.12,
        "branch_collar": 0.92, "dead_branch_probability": 0.06, "prune_probability": 0.05,
        "foliage_density": 0.50, "foliage_start": 0.64, "foliage_tip_bias": 0.82,
        "foliage_spread": 0.58, "leaf_up_bias": 0.60,
        "card_scale": 0.76, "card_aspect": 1.18, "card_style": "TRI",
    },
    "PINE": {
        "height": 20.0, "base_radius": 0.52, "trunk_irregularity": 0.055, "trunk_taper": 1.18,
        "root_flare": 0.30, "crown_shape": "CONICAL", "branch_distribution": "WHORLED",
        "branch_levels": 3, "branch_start": 0.18, "primary_branches": 36, "secondary_per_branch": 3,
        "branch_angle": 1.28, "branch_length": 5.5, "branch_length_randomness": 0.24,
        "branch_bend": 0.08, "branch_droop": 0.22, "apical_dominance": 0.88, "phototropism": 0.12,
        "branch_collar": 0.22, "dead_branch_probability": 0.045, "prune_probability": 0.07,
        "foliage_density": 1.45, "foliage_start": 0.48, "foliage_tip_bias": 0.70,
        "foliage_spread": 0.30, "leaf_up_bias": 0.48,
        "card_scale": 0.62, "card_aspect": 1.70, "card_style": "TRI",
    },
    "STONE_PINE": {
        "height": 17.0, "base_radius": 0.54, "trunk_irregularity": 0.07, "trunk_taper": 1.05,
        "root_flare": 0.31, "crown_shape": "UMBRELLA", "branch_distribution": "WHORLED",
        "branch_levels": 3, "branch_start": 0.55, "primary_branches": 19, "secondary_per_branch": 4,
        "branch_angle": 1.26, "branch_length": 6.0, "branch_length_randomness": 0.24,
        "branch_bend": 0.10, "branch_droop": 0.08, "apical_dominance": 0.44, "phototropism": 0.10,
        "branch_collar": 0.28, "dead_branch_probability": 0.045, "prune_probability": 0.09,
        "foliage_density": 1.30, "foliage_start": 0.55, "foliage_tip_bias": 0.75,
        "foliage_spread": 0.43, "leaf_up_bias": 0.52,
        "card_scale": 0.66, "card_aspect": 1.72, "card_style": "TRI",
    },
    "SPRUCE": {
        "height": 24.0, "base_radius": 0.56, "trunk_irregularity": 0.035, "trunk_taper": 1.25,
        "root_flare": 0.30, "crown_shape": "CONICAL", "branch_distribution": "WHORLED",
        "branch_levels": 3, "branch_start": 0.12, "primary_branches": 44, "secondary_per_branch": 3,
        "branch_angle": 1.36, "branch_length": 5.8, "branch_length_randomness": 0.16,
        "branch_bend": 0.06, "branch_droop": 0.42, "apical_dominance": 0.94, "phototropism": 0.16,
        "branch_collar": 0.18, "dead_branch_probability": 0.06, "prune_probability": 0.06,
        "foliage_density": 1.75, "foliage_start": 0.42, "foliage_tip_bias": 0.66,
        "foliage_spread": 0.26, "leaf_up_bias": 0.42,
        "card_scale": 0.54, "card_aspect": 1.85, "card_style": "TRI",
    },
    "FIR": {
        "height": 23.0, "base_radius": 0.55, "trunk_irregularity": 0.025, "trunk_taper": 1.22,
        "root_flare": 0.28, "crown_shape": "CONICAL", "branch_distribution": "WHORLED",
        "branch_levels": 3, "branch_start": 0.16, "primary_branches": 40, "secondary_per_branch": 3,
        "branch_angle": 1.38, "branch_length": 5.4, "branch_length_randomness": 0.12,
        "branch_bend": 0.045, "branch_droop": 0.12, "apical_dominance": 0.94, "phototropism": 0.18,
        "branch_collar": 0.18, "dead_branch_probability": 0.035, "prune_probability": 0.055,
        "foliage_density": 1.65, "foliage_start": 0.44, "foliage_tip_bias": 0.67,
        "foliage_spread": 0.28, "leaf_up_bias": 0.48,
        "card_scale": 0.56, "card_aspect": 1.80, "card_style": "TRI",
    },
    "CEDAR": {
        "height": 20.0, "base_radius": 0.62, "trunk_irregularity": 0.08, "trunk_taper": 1.02,
        "root_flare": 0.36, "crown_shape": "CONICAL", "branch_distribution": "WHORLED",
        "branch_levels": 4, "branch_start": 0.22, "primary_branches": 30, "secondary_per_branch": 4,
        "branch_angle": 1.34, "branch_length": 6.5, "branch_length_randomness": 0.25,
        "branch_bend": 0.11, "branch_droop": 0.14, "apical_dominance": 0.70, "phototropism": 0.10,
        "branch_collar": 0.24, "dead_branch_probability": 0.045, "prune_probability": 0.05,
        "foliage_density": 1.25, "foliage_start": 0.50, "foliage_tip_bias": 0.72,
        "foliage_spread": 0.36, "leaf_up_bias": 0.48,
        "card_scale": 0.64, "card_aspect": 1.65, "card_style": "TRI",
    },
    "CYPRESS": {
        "height": 20.0, "base_radius": 0.38, "trunk_irregularity": 0.025, "trunk_taper": 1.20,
        "root_flare": 0.18, "crown_shape": "COLUMNAR", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 3, "branch_start": 0.10, "primary_branches": 48, "secondary_per_branch": 3,
        "branch_angle": 0.34, "branch_length": 1.65, "branch_length_randomness": 0.14,
        "branch_bend": 0.035, "branch_droop": 0.0, "apical_dominance": 0.96, "phototropism": 0.72,
        "branch_collar": 0.14, "dead_branch_probability": 0.01, "prune_probability": 0.03,
        "foliage_density": 1.85, "foliage_start": 0.35, "foliage_tip_bias": 0.60,
        "foliage_spread": 0.18, "leaf_up_bias": 0.78,
        "card_scale": 0.48, "card_aspect": 1.55, "card_style": "TRI",
    },
    "REDWOOD": {
        "height": 55.0, "base_radius": 1.35, "trunk_irregularity": 0.025, "trunk_taper": 1.16,
        "root_flare": 0.85, "crown_shape": "CONICAL", "branch_distribution": "WHORLED",
        "branch_levels": 3, "branch_start": 0.18, "primary_branches": 52, "secondary_per_branch": 3,
        "branch_angle": 1.30, "branch_length": 9.0, "branch_length_randomness": 0.20,
        "branch_bend": 0.055, "branch_droop": 0.16, "apical_dominance": 0.96, "phototropism": 0.20,
        "branch_collar": 0.28, "dead_branch_probability": 0.055, "prune_probability": 0.08,
        "foliage_density": 1.48, "foliage_start": 0.48, "foliage_tip_bias": 0.70,
        "foliage_spread": 0.34, "leaf_up_bias": 0.48,
        "card_scale": 0.72, "card_aspect": 1.70, "card_style": "TRI",
    },
    "DEAD_TREE": {
        "height": 13.0, "base_radius": 0.62, "trunk_irregularity": 0.34, "trunk_taper": 0.76,
        "root_flare": 0.66, "crown_shape": "ROUND", "branch_distribution": "RANDOM",
        "branch_levels": 4, "branch_start": 0.22, "primary_branches": 14, "secondary_per_branch": 3,
        "branch_angle": 1.08, "branch_length": 5.3, "branch_length_randomness": 0.52,
        "branch_bend": 0.38, "branch_droop": 0.20, "apical_dominance": 0.10, "phototropism": 0.0,
        "branch_collar": 0.48, "dead_branch_probability": 0.62, "prune_probability": 0.30,
        "foliage_density": 0.0, "foliage_start": 0.70, "foliage_tip_bias": 0.90,
        "foliage_spread": 0.25, "leaf_up_bias": 0.40,
        "card_scale": 0.55, "card_aspect": 1.20, "card_style": "SINGLE",
    },
    "WINDSWEPT": {
        "height": 9.0, "base_radius": 0.46, "trunk_irregularity": 0.30, "trunk_taper": 0.82,
        "root_flare": 0.56, "crown_shape": "UMBRELLA", "branch_distribution": "RANDOM",
        "branch_levels": 3, "branch_start": 0.25, "primary_branches": 13, "secondary_per_branch": 3,
        "branch_angle": 1.30, "branch_length": 5.0, "branch_length_randomness": 0.48,
        "branch_bend": 0.42, "branch_droop": 0.28, "apical_dominance": 0.10, "phototropism": 0.02,
        "branch_collar": 0.42, "dead_branch_probability": 0.16, "prune_probability": 0.14,
        "foliage_density": 0.58, "foliage_start": 0.60, "foliage_tip_bias": 0.82,
        "foliage_spread": 0.46, "leaf_up_bias": 0.42,
        "card_scale": 0.62, "card_aspect": 1.24, "card_style": "CROSS",
    },
    "SAPLING": {
        "height": 4.0, "base_radius": 0.11, "trunk_irregularity": 0.055, "trunk_taper": 1.15,
        "root_flare": 0.12, "crown_shape": "OVAL", "branch_distribution": "PHYLLOTAXIS",
        "branch_levels": 2, "branch_start": 0.30, "primary_branches": 10, "secondary_per_branch": 2,
        "branch_angle": 0.92, "branch_length": 1.45, "branch_length_randomness": 0.24,
        "branch_bend": 0.08, "branch_droop": 0.04, "apical_dominance": 0.78, "phototropism": 0.42,
        "branch_collar": 0.14, "dead_branch_probability": 0.0, "prune_probability": 0.015,
        "foliage_density": 0.88, "foliage_start": 0.52, "foliage_tip_bias": 0.74,
        "foliage_spread": 0.34, "leaf_up_bias": 0.65,
        "card_scale": 0.34, "card_aspect": 1.25, "card_style": "CROSS",
    },
}


def apply_preset(settings, name):
    preset = PRESETS.get(name)
    if not preset:
        return False
    for key, value in preset.items():
        if hasattr(settings, key):
            setattr(settings, key, value)
    return True
